"""
This module contains a simple yet convenient approach to solving the standard Toy Robot 4  maze
"""

from world import world
import movement_logics


def world_pos_tracker(turtle_variable):
    """
    tracks the x-axis and the y-axis position of the robot
    Then returns a message of the robots current position in the world

    Args:
        robot_name (str): The name of the robot
        turtle_variable : the turtle_name of the robot
        
    Returns:
        list: The robot's current position on the world map
        int : The robot's current degree of orientation
        string: message on the robots whereabouts
    """
    
    # retrieving the position of the turtle
    robot_position = turtle_variable.pos()
    # retrieves the degree that turtle is facing
    degree = turtle_variable.heading()
    
    # converting the returned float into int
    position = []
    for pos in robot_position:
        position.append(int(pos))
        
    # returning the message of the robots position 
    # message = f" > {robot_name} now at position {tuple(position)}."
    return position,degree


def command_splitter(command: str):
    """Splits the command into two parts, command and parameter

    Args:
        command (str): command given to the robot

    Returns:
        list: the list consists of the command and its parameter if any
    """

    commands = command.split(" ")
    return commands


def command_handler(robot_name,command,x,y,degree,turtle_variable,obstacle):

    # The command is split in two parts in list format [Command, Parameter]
    # in our com_n_par list, the command is always at index 0
    command = command_splitter(command)


    if "Right" in command or "Left" in command:
        x,y,degree,message,invalid_com = movement_logics.turn_logic(robot_name,command,x,y,degree,turtle_variable)
    else:
        x,y,degree,message,invalid_com = movement_logics.movement_logic(robot_name,command,x,y,degree,turtle_variable,obstacle)
        
    return x,y,degree, message, invalid_com


def generate_steps_command(x,y,current_degree,cell_size):
    """
    Generates a command that gets fed into the command handler.
    The command handler is in charge of controlling the robots movement, thus based
    of the command that gets generated by this function, the robot shell execute what needs to be done

    Args:
        x (int): the robots current x coordinate
        y (int): the robots current y coordinate
        current_degree (int): the robots current degree of orientation
        cell_size (int): teh size of a single cell in our maze grid

    Returns:
        str : the command that the robot needs to execute
    """

    if current_degree == 0 and x + cell_size > 100:
        command = " ".join(['Forward',f'{100 - x}'])

    elif current_degree == 180 and x - cell_size < - 100:
        command = " ".join(['Forward',f'{100 + x}'])

    elif current_degree == 90 and y + cell_size > 200:
        command = " ".join(['Forward',f'{200 - y}'])

    elif current_degree == 270 and y - cell_size < - 200:
        command = " ".join(['Forward',f'{200 + y}'])

    else:
        command = " ".join(['Forward',f'{cell_size}'])
        
    return command

def fix_degree(current_degree):
    """
    Converts the negative degree to its corresponding positive degree
    Args:
        current_degree (int): the turtles current degree

    Returns:
        int : the corresponding positive degree
    """

    if current_degree == -270:
        current_degree = 90
    elif current_degree == -90:
        current_degree = 270
    elif current_degree == -180:
        current_degree = 180
    elif current_degree == 360:
        current_degree = 0

    return current_degree


def rotate_robot(actual_degree, current_degree):
    """
    Calculates the number of times to turn the robot left/right
    so that it is facing the correct direction that it needs to move forward in

    Args:
        actual_degree (int): the degree the robot needs to be facing in order to move forward in the specified direction
        current_degree (int): the degree the robot is currently facing
    Returns:
        int : the number of times the robot needs to turn and in what direction (- left / + right)
    """
    
    north = [90,-270]
    south = [-90,270]
    east = [0,360]
    west = [180,-180]

    turn = ['Right','Right']

    if current_degree in north:
        # the idea is if we by 90/-270 and we want to go to 180
        if actual_degree in north:
            return None
        
        if actual_degree in west:
            turn = ['Left']
        elif actual_degree in east:
            turn = ['Right']

    elif current_degree in south:
        
        if actual_degree in south:
            return None

        if actual_degree in east:
            turn = ['Left']
        elif actual_degree in west:
            turn = ['Right']

    elif current_degree in east:
        
        if actual_degree in east:
            return None
        
        if actual_degree in north:
            turn = ['Left']
        elif actual_degree in south:
            turn = ['Right']

    else:
        
        if actual_degree in west:
            return None
        
        if actual_degree in north:
            turn = ['Right']
        elif actual_degree in south:
            turn = ['Left']

    return turn



def find_cell(cells_ref,x,y,cell_Size):
    # not required to solve a simple maze
    return None,None,None

def maze_run(cells_ref,exit_points, obstacle_ref,current_cell,visited_cells,height,width,cells_size,hunt,turtle_variable,x,y,degree):
    # not required to solve a simple maze

    return None


def solve_maze(coordinates,robot_name,turtle_variable,path_taken,cells_ref,obstacles,factor, hunt = "top",cell_size = 4, unit = 1.5):
    """
    Using the corresponding robot, solve maze will issue a set of commands that will enable the robot
    to traverse through the maze to the corresponding edge of the maze if specified.
    By default the robot will traverse to the top edge of the maze

    Args:
        cords (tuple): a tuple containing the x and y coordinate and the degree of the robot
        robot_name (str): the name of th robot
        turtle_variables (object): the turtle object (used to move the turtle gui)
        path_taken (list): a list containing all the indexes of the cells that we need to move to in order to solve the maze
        cell_ref (list): a list of all the cells in our maze grid
        obstacles (list): a list of all the obstacles in our maze grid
        factor (int): factor is the max number of cells we can hold in a single column (height / cell_size)
        hunt (str, optional): the edge of teh maze we wish to solve to. Defaults to "top".
        cell_size (int, optional): the size of a single cell in the maze grid. Defaults to 4.


    Returns:
        tuple: x,y,current_degree - the robots new position in the maze grid once it has finished traversing the maze
    """
    
    
    robot_name = robot_name
    x,y,current_degree = coordinates

    targets = {"top":200, "bottom":-200, "right":100, "left":-100}
    target_degrees = {"top":90, "bottom":270, "right":0, "left":180}

    target = {target for key,target in targets.items() if hunt == key}.pop()
    target_degree = {degree for key,degree in target_degrees.items() if hunt == key}.pop()


    dodge_obstacles = None
    while True:



        turns = rotate_robot(target_degree,current_degree)

        if turns != None:
            for command in turns:
                x,y,current_degree,message,invalid = command_handler(robot_name,command,x,y,current_degree,turtle_variable,obstacles)
                coordinates=(x,y,current_degree)
                world.position_tracker(robot_name,coordinates,turtle_variable)

        command = generate_steps_command(x,y,current_degree,cell_size)
        x,y,current_degree,message,invalid = command_handler(robot_name,command,x,y,current_degree,turtle_variable,obstacles)
        coordinates=(x,y,current_degree)
        world.position_tracker(robot_name,coordinates,turtle_variable)

        if target_degree in [0,180]:
            dodge_it = x
        else:
            dodge_it = y

        # changes the direction that the robot is facing when it encounters an obstacle
        if dodge_it == dodge_obstacles and current_degree == target_degree:
            # current_degree is the current degree fo teh direction the robot is facing
            x,y,current_degree,message,invalid = command_handler(robot_name,"Right",x,y,current_degree,turtle_variable,obstacles)
            coordinates=(x,y,current_degree)
            world.position_tracker(robot_name,coordinates,turtle_variable)

            command = generate_steps_command(x,y,current_degree,4)
            x,y,current_degree,message,invalid = command_handler(robot_name,command,x,y,current_degree,turtle_variable,obstacles)
            coordinates=(x,y,current_degree)
            world.position_tracker(robot_name,coordinates,turtle_variable)

        # here we setting the dodging value (value of x/y) the same as the previous (x/y)
        # in the next iteration if these two values are equal that is how we know that we
        # have not moved forward, thus there is something blocking us (An obstacle)
        dodge_obstacles = dodge_it
        current_degree = fix_degree(current_degree)

        if target_degree == current_degree and dodge_it == target:
            return x,y,current_degree



